apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "raidchain.fullname" . }}-scripts
data:
  entrypoint-chain.sh: |-
    {{- .Files.Get "scripts/entrypoint-chain.sh" | nindent 4 }}
  init-relayer.sh: |-
    {{- .Files.Get "scripts/init-relayer.sh" | nindent 4 }}
  # 追加
  init-register.sh: |-
    {{- .Files.Get "scripts/init-register.sh" | nindent 4 }}