{{- if .Values.gwc }}
{{- $chain := merge (dict "name" "gwc") .Values.gwc }}
{{- include "cryptomeria.chain.statefulset-template" (dict "Value" $chain "Release" .Release "Values" .Values "Chart" .Chart) }}
{{- end }}