{{- if .Values.mdsc }}
{{- $chain := merge (dict "name" "mdsc") .Values.mdsc }}
{{- include "cryptomeria.chain.statefulset-template" (dict "Value" $chain "Release" .Release "Values" .Values "Chart" .Chart) }}
{{- end }}