{{- if .Values.fdsc }}
{{- $count := int .Values.fdsc.replicas }}
{{- range $i := until $count }}
{{- $chain := deepCopy $.Values.fdsc }}
{{- $_ := set $chain "name" "fdsc" }}
{{- $_ := set $chain "index" $i }}
{{- include "cryptomeria.chain.statefulset-template" (dict "Value" $chain "Release" $.Release "Values" $.Values "Chart" $.Chart) }}
{{- end }}
{{- end }}