{{- if .Values.relayer.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cryptomeria.fullname" . }}-relayer-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptomeria.labels" . | nindent 4 }}
    app.kubernetes.io/component: relayer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # ▼ 修正: .Values.relayer.storage.size -> .Values.relayer.persistence.size
      storage: {{ .Values.relayer.persistence.size }}
{{- end }}