apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cryptomeria.fullname" . }}-scripts
  labels:
    {{- include "cryptomeria.labels" . | nindent 4 }}
data:
  entrypoint-chain.sh: |
{{ include "cryptomeria.scripts.entrypoint" . | indent 4 }}