apiVersion: v1
kind: Service
metadata:
  name: {{ include "cryptomeria.fullname" . }}-chain-headless
  labels:
      app.kubernetes.io/name: cryptomeria
      app.kubernetes.io/category: chain
spec:
  clusterIP: None
  ports:
    - name: rpc
      port: 26657
    - name: grpc
      port: 9090
    - name: api
      port: 1317
  selector:
    app.kubernetes.io/name: cryptomeria
    app.kubernetes.io/category: chain