apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cryptomeria.fullname" . }}-genesis-script
  labels:
    {{- include "cryptomeria.labels" . | nindent 4 }}
data:
  generate.sh: |
{{ include "cryptomeria.scripts.genesis" . | indent 4 }}