{{- if and .Values.gwc .Values.gwc.service.externalService.enabled }}
{{- $chain := merge (dict "name" "gwc") .Values.gwc }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cryptomeria.fullname" . }}-gwc
  labels:
    {{- include "cryptomeria.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ $chain.name }}
spec:
  type: {{ $chain.service.externalService.type | default "NodePort" }}
  ports:
    - name: rpc
      port: {{ $chain.service.rpcPort }}
      targetPort: {{ $chain.service.rpcPort }}
      nodePort: {{ add .Values.ports.gwcBase 7 }}
    - name: api
      port: {{ $chain.service.apiPort }}
      targetPort: {{ $chain.service.apiPort }}
      nodePort: {{ add .Values.ports.gwcBase 3 }}
    - name: grpc
      port: {{ $chain.service.grpcPort }}
      targetPort: {{ $chain.service.grpcPort }}
      nodePort: {{ .Values.ports.gwcBase }}
  selector:
    app.kubernetes.io/name: cryptomeria
    app.kubernetes.io/category: chain
    app.kubernetes.io/instance: {{ $chain.name }}
{{- end }}