# Default values for cryptomeria.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullPolicy: IfNotPresent # 開発中は Always 推奨, 本番は IfNotPresent

chains:
  - name: gwc
    type: gwc
  - name: mdsc
    type: mdsc
  - name: fdsc-0
    type: fdsc
  - name: fdsc-1
    type: fdsc

chainTypes:
  gwc:
    repository: cryptomeria/gwc
    tag: latest
  mdsc:
    repository: cryptomeria/mdsc
    tag: latest
  fdsc:
    repository: cryptomeria/fdsc
    tag: latest

relayer:
  repository: cryptomeria/relayer
  tag: latest
  # 【追加】リレイヤーの永続化設定
  storage:
    size: 1Gi

# 全チェーン共通の設定
chain:
  storage:
    size: 1Gi

# 環境変数 (共通)
env:
  - name: CHAIN_ID_PREFIX
    value: "cryptomeria"