# Default values for cryptomeria.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullPolicy: IfNotPresent # 開発中は Always 推奨, 本番は IfNotPresent

chains:
  - name: gwc
    type: gateway
  - name: mdsc
    type: metastore
  # FDSCの数はコマンドライン引数などで動的に増やす想定
  # generate-values.sh で上書きされる
  - name: fdsc-0
    type: datastore
  - name: fdsc-1
    type: datastore

chainTypes:
  gateway:
    repository: cryptomeria/gwc
    tag: latest
  metastore:
    repository: cryptomeria/mdsc
    tag: latest
  datastore:
    repository: cryptomeria/fdsc
    tag: latest

relayer:
  repository: cryptomeria/relayer
  tag: latest
  # 【追加】リレイヤーの永続化設定
  storage:
    size: 1Gi

# 全チェーン共通の設定
chain:
  storage:
    size: 1Gi
    className: standard

# 環境変数 (共通)
env:
  - name: CHAIN_ID_PREFIX
    value: "cryptomeria"